#kotlin/exception

# Wyjątek

>[!tip] Wyjątek
>wyjątek jest pewnego rodzaju **ostrzeżeniem** przed wyjątkowymi sytuacjami, jakie zachodzą podczas wykonywania programu. 
>To tak, jakby kod mówił: *Zawiodłem, stało się coś złego*.

>[!info] Wyjątek
>Każdy wyjątek jest obiektem typu `Exception`. 
>To klasa bazowa wszystkich wyjątków, więc dziedziczą po niej wszystkie inne typy wyjątków.

PRZYKŁADOWE klasy wyjątków:
- `NullPointerException` Ten wyjątek jest zgłaszany, kiedy spróbujemy wykonać jakąś operację na wartości `null`. Jak już sam się przekonałeś, w Kotliczynie wyjątki `NullPointerException` są uważane za gatunek wymierający.
- `ClassCastException` Ten wyjątek jest zgłaszany, kiedy próbujemy rzutować obiekt na nieodpowiedni typ, na przykład obiekt `Wolf` na `Tree`.
- `IllegalArgumentException` Ten wyjątek możesz zgłosić, jeśli zostaną przekazane argumenty nieodpowiednich typów.
- `IllegalStateException` Skorzystaj z tego wyjątku, jeśli jakieś obiekty znajdą się w nieprawidłowym stanie.

WŁASNA KLASA WYJĄTKÓW:
```kotlin
class AnimalException : Exception(){

}
```


# Przechwytywanie wyjątków - `try`, `catch`
Gdy wystąpi wyjątek, można:
1. zostawić wyjątek -> przerwania działania aplikacji
2. przechwycić wyjątek i go obsłużyć `try catch`
	1. Wyjątki można przechwytywać, umieszczając potencjalnie ryzykowny kod w bloku *try/catch*.
	2. Użycie tego bloku informuje kompilator, że wiemy, że w danym kodzie może wystąpić wyjątkowa sytuacja, oraz że jesteśmy przygotowani na jej obsłużenie.

```kotlin

fun myFunction(str: String) {
	try {
		val x = str.toInt() println(x)
	
	} catch (e: NumberFormatException) {
		println(“A to pech!”)
	}

	println(”Funkcja myFunction kończy działanie”) 

}
```

## `finally` - czynności, które zawsze mają być wykonane

przykład:
```kotlin
try {
	turnOvenOn() 
	x.bake()

} catch (e: BakingException) {
	println(“Eksperymentalny wypiek zakończył się katastrofą!”)

} finally { 
	turnOvenOff()
}
```
równoważny kod (nadmiarowe `turnOvenOff`)
```kotlin
try {
	turnOvenOn() x.bake()
	turnOvenOff()
} catch (e: BakingException) {
	println(“Eksperymentalny wypiek zakończył się katastrofą!”)
	turnOvenOff()
}
```

# Jawne zgłaszanie wyjątków - `throw`

```kotlin
fun setWorkRatePercentage(x: Int) { 
	
	if (x !in 0..100) {
		throw IllegalArgumentException(“Wartość procentowa poza zakresem 0..100: $x”)
	}

// Kod wykonywany, jeśli argument jest prawidłowy.

}
```

PRZECHWYCENIE TEGO WYJĄTKU
```kotlin
try { 
	setWorkRatePercentage(110) 
} catch(e: IllegalArgumentException) {
	// Kod obsługujący wyjątek.
}
```

Za blokiem `try` musi wystąpić blok catch lub `finally`:
```kotlin
try { callRiskyCode() } finally { }
```

Za blokiem try można umieścić wiele bloków catch:
```kotlin
try { callRiskyCode() } 
catch (e: BadException) { } 
catch (e: ScaryException) { }
```


# `Try` , `catch`, `throw` to wyrażenia

## `try` i `catch`
„Spróbuj zapisać str.toInt() w zmiennej result, a jeśli nie możesz tego zrobić, to zapisz w niej null”.:
```kotlin
val result = try { str.toInt() } catch (e: Exception) { null }
```

## `throw`
Jeśli zmienna `w` i jej właściwość `hunger` będą różne od `null`, to w nowej zmiennej `h` zostanie zapisana wartość właściwości. 
Jeżeli jednak zmienna `w` bądź jej właściwość `hunger` przyjmą wartość `null`, to zostanie zgłoszony wyjątek `AnimalException`.
```kotlin
val h = w?.hunger? ?: throw AnimalException()
```








